### ISSUE TITLE
Cannot attach Cassandra-Connector

### ISSUE THREAD

**Issue by austindsouza** [Stratio/stratio-connector-cassandra#2]
Hi ,
I am trying to run the crossdata-client-examples by installing Crossdata-0.3.0-RC3-SNAPSHOT,
Started Crossdata server first and then started shell, then i started connectors of Cassandra and Deep.

After that i added DATASTORE, ATTACHED CLUSTER, ADDED CONNECTOR
While adding CONNECTOR i faced an exception:

[Driver] 30-05-2015 14:48:43.291 [ERROR|BasicDriver$] CrossdataManifest couldn't be parsed
Error parsing manifest: 
com.stratio.crossdata.common.exceptions.ManifestException: javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 13; cvc-complex-type.2.4.a: Invalid content was found starting with element 'Native'. One of '{RequiredProperties, OptionalProperties, SupportedOperations, Functions}' is expected.]

and then i deleted the <native>true</native> from the pom file..... after that connector is added sucessfully.
# When i do Attach Connector to Cluster i got an error:

xdsh:root> ATTACH CONNECTOR CassandraConnector TO cassandra_prod WITH OPTIONS {'DefaultLimit': '1000'};
[Driver] 30-05-2015 14:52:16.061 [INFO|Shell] Query 77fd362c-5b75-4a85-ad79-7c289e71d147 in progress

xdsh:root> 
Result: The operation for query 77fd362c-5b75-4a85-ad79-7c289e71d147 cannot be executed:
Connector connector.CassandraConnector is not connected.
# When i give DESCRIBE CONNECTORS it shows:

xdsh:root:catalogTest> describe connectors;
[Driver] 30-05-2015 15:35:23.939 [INFO|Shell] 
Connector: connector.CassandraConnector OFFLINE []  [datastore.Cassandra]   UNKNOWN
Connector: connector.DeepConnector  ONLINE  [cluster.cassandra_prod, cluster.cassandra_clust]   [datastore.elasticsearch, datastore.cassandra, datastore.mongo, datastore.hdfs, datastore.jdbc, datastore.aerospike]    [akka.tcp://CrossdataServerCluster@127.0.0.1:34372/user/ConnectorActor/]

But i have Started both Cassandra and Deep connector by using the command:
target/cassandra-connector-0.4.0-SNAPSHOT/bin/cassandra-connector-0.4.0-SNAPSHOT start
target/stratio-connector-deep-0.4.0-SNAPSHOT/bin/stratio-connector-deep-0.4.0-SNAPSHOT start

Please help me what's gone wrong in this.

Thanks!

**Comment by mafernandez-stratio** [comment]
Hi Austin,

which version of the Cassandra Connector are you using?

**Comment by jjlopezm** [comment]
Hi Austin,
The problem is you are using incompatible versions between Crossdata and Cassandra Connector.
You have two different solutions:
1. You can use our brand new release of Crossdata and Cassandra Connector (version 0.3.0). You can obtain those versions of the 0.3.0-RELEASE tag as well as the branch0.3. If you will do that you can follow the stepts that you did before without any problem.
1. You can use our new 0.4.0-SNAPSHOT version of Crossadata, and the same version of Cassandra Connector, (obtain that of the master of github project) and you can avoid the steps of the ADD DATASTORE and ADD CONNECTOR because this steps will execute automatically.

Please tell me if you have any more problems.

**Comment by austindsouza** [comment]
Hi,

I am using crossdata cassandra-connector 0.4.0 SNAPSHOT

**Comment by mafernandez-stratio** [comment]
Hi Austin,

as my colleague jjlopezm said, you should use a version 0.3.X of Crossdata with a version version 0.3.X of the Cassandra Connector or a version 0.4.X of Crossdata with a version 0.4.X of the Cassandra Connector.

Please, let us know if this solves the issue.

**Comment by austindsouza** [comment]
Hi Miguel & Jjlopezm,

Thanks for your suggestions, i changed the version of Cassandra connector to 0.3.0 now its working fine.

Thank you!
