### ISSUE TITLE
 CrossdataManifest couldn't be parsed

### ISSUE THREAD

**Issue by austindsouza** [Stratio/stratio-connector-cassandra#3]
Hi,

I installed a new Stratio-Cassandra with Lucene 2.1.5 and Also updated Stratio-Cassandra-Connector Version No 0.4.0-SNAPSHOT

But when i installing Stratio Crossdata to attach a new Connector to Cluster i got an ERROR

xdsh:root> ADD CONNECTOR /home/tg1//target/cassandra-connector-0.4.0-SNAPSHOT/conf/CassandraConnector.xml;
[Driver] 07-07-2015 16:34:05.383 [ERROR|BasicDriver$] CrossdataManifest couldn't be parsed
Error parsing manifest: 
com.stratio.crossdata.common.exceptions.ManifestException: javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 13; cvc-complex-type.2.4.a: Invalid content was found starting with element 'Native'. One of '{RequiredProperties, OptionalProperties, SupportedOperations, Functions}' is expected.]
  at com.stratio.crossdata.driver.utils.ManifestUtils$.parseFromXmlToConnectorManifest(ManifestUtils.scala:101)
  at com.stratio.crossdata.driver.utils.ManifestUtils$.parseFromXmlToManifest(ManifestUtils.scala:49)
  at com.stratio.crossdata.driver.BasicDriver.addManifest(BasicDriver.scala:545)
  at com.stratio.crossdata.driver.BasicDriver.sendManifest(BasicDriver.scala:383)
  at com.stratio.crossdata.driver.BasicDriver.executeApiCall(BasicDriver.scala:299)
  at com.stratio.crossdata.driver.BasicDriver.executeAsyncRawQuery(BasicDriver.scala:256)
  at com.stratio.crossdata.sh.Shell.executeAsyncRawQuery(Shell.java:416)
  at com.stratio.crossdata.sh.Shell.loop(Shell.java:376)
  at com.stratio.crossdata.sh.Shell.main(Shell.java:163)
  Caused by: javax.xml.bind.UnmarshalException
## In Prerequisite column It is given that 

Cassandra version 2.1.6 must be installed and started.
Crossdata version 0.4.0-SNAPSHOT is needed to interact with this connector.
but i did not find Crossdata 0.4.0 version in repository, it is still 0.3.4.

Can u please upload the New version of Crossdata

Thanks!

**Comment by jjlopezm** [comment]
The 0.4.0-SNAPSHOT version is in Master branch. Please checkout to this
branch and the problem with the manifest will be resolved.

On Tue, Jul 7, 2015 at 1:52 PM, Austin Solomon notifications@github.com
wrote:

> Hi,
> 
> I installed a new Stratio-Cassandra with Lucene 2.1.5 and Also updated
> Stratio-Cassandra-Connector Version No 0.4.0-SNAPSHOT
> 
> But when i installing Stratio Crossdata to attach a new Connector to
> Cluster i got an ERROR
> 
> xdsh:root> ADD CONNECTOR
> /home/tg1//target/cassandra-connector-0.4.0-SNAPSHOT/conf/CassandraConnector.xml;
> [Driver] 07-07-2015 16:34:05.383 [ERROR|BasicDriver$] CrossdataManifest
> couldn't be parsed
> Error parsing manifest:
> com.stratio.crossdata.common.exceptions.ManifestException:
> javax.xml.bind.UnmarshalException
> - with linked exception: [org.xml.sax.SAXParseException; lineNumber:
>   8; columnNumber: 13; cvc-complex-type.2.4.a: Invalid content was found
>   starting with element 'Native'. One of '{RequiredProperties,
>   OptionalProperties, SupportedOperations, Functions}' is expected.] at
>   com.stratio.crossdata.driver.utils.ManifestUtils$.parseFromXmlToConnectorManifest(ManifestUtils.scala:101)
>   at
>   com.stratio.crossdata.driver.utils.ManifestUtils$.parseFromXmlToManifest(ManifestUtils.scala:49)
>   at
>   com.stratio.crossdata.driver.BasicDriver.addManifest(BasicDriver.scala:545)
>   at
>   com.stratio.crossdata.driver.BasicDriver.sendManifest(BasicDriver.scala:383)
>   at
>   com.stratio.crossdata.driver.BasicDriver.executeApiCall(BasicDriver.scala:299)
>   at
>   com.stratio.crossdata.driver.BasicDriver.executeAsyncRawQuery(BasicDriver.scala:256)
>   at com.stratio.crossdata.sh.Shell.executeAsyncRawQuery(Shell.java:416) at
>   com.stratio.crossdata.sh.Shell.loop(Shell.java:376) at
>   com.stratio.crossdata.sh.Shell.main(Shell.java:163) Caused by:
>   javax.xml.bind.UnmarshalException
> 
> In Prerequisite column It is given that
> 
> Cassandra version 2.1.6 must be installed and started.
> Crossdata version 0.4.0-SNAPSHOT is needed to interact with this connector.
> but i did not find Crossdata 0.4.0 version in repository, it is sitll
> 0.3.4.
> 
> Can u please upload the New version of Crossdata
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Stratio/stratio-connector-cassandra/issues/3.

## 

Juanjo Lopez

Via de las Dos Castillas, 33. Ática 4. 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: 91 352 59 42 // @stratiobd

**Comment by austindsouza** [comment]
Ok, I will check it and let you know. 
Thanks for the reply..... :)

**Comment by austindsouza** [comment]
Hi ,
I have a Twitter table in Crossdata Cataloge and i am using cassandra connector,
When i querry the table 
...............................................................................................................................................................
xdsh:root:DemoTwitter> SELECT \* FROM IndexTweet WHERE CreatedAt >= '2015-07-10 10:41:44+0530' AND  CreatedAt <= '2015-07-10 10:43:44+0530'  LIMIT 10;
[Driver] 11-07-2015 12:58:15.601 [INFO|Shell] Query 699cd2ca-3fb7-45e7-9ad1-42d2c2a85e95 in progress
xdsh:root:DemoTwitter> 
Result: The operation for query 699cd2ca-3fb7-45e7-9ad1-42d2c2a85e95 cannot be executed:
Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING
...............................................................................................................................................................

and if i give ALLOW FILTER to this querry i am getting 

Parser exception: 
    Error recognized: line 1:139: required (...)+ loop did not match anything at input 'ALLOW'
    SELECT \* FROM IndexTweet WHERE CreatedAt >= '2015-07-10 10:41:44+0530' AND CreatedAt <= '2015-07-10 10:43:44+0530' LIMIT 10 ?ALLOW FILTERING;

Please tell me what is the problem?
I am usind Apache Cassandra 2.1.7
Crossdata 0.4.0
Cassandra Connector 0.4.0.

**Comment by jjlopezm** [comment]
Hi again,

Nowadays Crossdata hasn't implement the ALLOW FILTERING command, because
it's very inefficient. Please see this datastax  doc and you can see the
reasons of why Crossdata are not implemented allow filtering.

http://www.datastax.com/dev/blog/allow-filtering-explained-2

One solution could be create a Lucene Index in CreatedAt column. Once you
have the lucene index, you can use the function range implemented in
Cassandra Connector. You can redesign the query like this:
SELECT \* FROM IndexTweet WHERE CreatedAt=range('2015-07-10 10:41:44','
2015-07-10
10:43:44');

I hope this solution works fine for your use case.

Juanjo

On Sat, Jul 11, 2015 at 9:33 AM, Austin Solomon notifications@github.com
wrote:

> Hi ,
> I have a Twitter table in Crossdata Cataloge and i am using cassandra
> connector,
> When i querry the table
> 
> ...............................................................................................................................................................
> xdsh:root:DemoTwitter> SELECT \* FROM IndexTweet WHERE CreatedAt >=
> '2015-07-10 10:41:44+0530' AND CreatedAt <= '2015-07-10 10:43:44+0530'
> LIMIT 10;
> [Driver] 11-07-2015 12:58:15.601 [INFO|Shell] Query
> 699cd2ca-3fb7-45e7-9ad1-42d2c2a85e95 in progress
> xdsh:root:DemoTwitter>
> Result: The operation for query 699cd2ca-3fb7-45e7-9ad1-42d2c2a85e95
> cannot be executed:
> Cannot execute this query as it might involve data filtering and thus may
> have unpredictable performance. If you want to execute this query despite
> the performance unpredictability, use ALLOW FILTERING
> 
> ...............................................................................................................................................................
> 
> and if i give ALLOW FILTER to this querry i am getting
> 
> Parser exception:
> Error recognized: line 1:139: required (...)+ loop did not match anything
> at input 'ALLOW'
> SELECT \* FROM IndexTweet WHERE CreatedAt >= '2015-07-10 10:41:44+0530' AND
> CreatedAt <= '2015-07-10 10:43:44+0530' LIMIT 10 ?ALLOW FILTERING;
> 
> Please tell me what is the problem?
> I am usind Apache Cassandra 2.1.7
> Crossdata 0.4.0
> Cassandra Connector 0.4.0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Stratio/stratio-connector-cassandra/issues/3#issuecomment-120592417
> .

## 

Juanjo Lopez

Via de las Dos Castillas, 33. Ática 4. 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: 91 352 59 42 // @stratiobd

**Comment by austindsouza** [comment]
Hi Juanjo,

Your solution of using 'range' worked fine for me.

Thanks for help!! :)
