### ISSUE TITLE
Crossdata Describe keyspace, parser exception

### ISSUE THREAD

**Issue by austindsouza** [Stratio/stratio-connector-cassandra#4]
Hi,
I am trying to get the Catalog metadata, tables from crossdata cluster programatically using java.

I am using the following code:
// USE
    xdConnection.setCurrentCatalog("TempTable");

```
// SELECT STATEMENT
System.out.println("listCassandraKeyspace entry=====>");
Result result = null;
String output="";

try {
    QueryResult qr = (QueryResult)xdConnection.executeQuery("DESCRIBE CATALOGS;");
    ResultSet rs=qr.getResultSet();
    ....
    }
```

When i run the above code, I did'nt get the catlogs list from the cluster, Instead i got the following ERROR,
com.stratio.crossdata.common.exceptions.ParsingException: Parser exception:
              Error recognized: line 1:19: no viable alternative at input 'DESCRIBE'
              ?DESCRIBE CATALOGS;

I googled the error and found that DESCRIBE is the shell command, and it is available only in shell interface. 
In Cassandra i can get the KEYSPACES by the command Select \* from system.schema_keyspaces;

Is there any alternatives to this in Crossdata.

Thank you in advance..
Austin

**Comment by jjlopezm** [comment]
Hi,
please try to use this method:

```
executeDescribe(command: String, sessionId: String):Result
```

instead of executeQuery method.

Let us know if this solution is OK for you.

Regards

On Mon, Jul 27, 2015 at 1:52 PM, Austin Solomon notifications@github.com
wrote:

> Hi,
> I am trying to get the Catalog metadata, tables from crossdata cluster
> programatically using java.
> 
> I am using the following code:
> // USE
> xdConnection.setCurrentCatalog("TempTable");
> 
> // SELECT STATEMENT
> System.out.println("listCassandraKeyspace entry=====>");
> Result result = null;
> String output="";
> 
> try {
>     QueryResult qr = (QueryResult)xdConnection.executeQuery("DESCRIBE CATALOGS;");
>     ResultSet rs=qr.getResultSet();
>     ....
>     }
> 
> When i run the above code, I did'nt get the catlogs list from the cluster,
> Instead i got the following ERROR,
> com.stratio.crossdata.common.exceptions.ParsingException: Parser exception:
> Error recognized: line 1:19: no viable alternative at input 'DESCRIBE'
> ?DESCRIBE CATALOGS;
> 
> I googled the error and found that DESCRIBE is the shell command, and it
> is available only in shell interface.
> In Cassandra i can get the KEYSPACES by the command Select \* from
> system.schema_keyspaces;
> 
> Is there any alternatives to this in Crossdata.
> 
> Thank you in advance..
> Austin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Stratio/stratio-connector-cassandra/issues/4.

## 

Juanjo Lopez

Via de las Dos Castillas, 33. Ática 4. 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: 91 352 59 42 // @stratiobd

**Comment by mafernandez-stratio** [comment]
Hi @austindsouza,

was this issue finally resolved?
